#!/bin/sh

# Copyright (C) 2018 and onwards LNCM Contributors

if [ -z "${BOXNAME}" ]; then
    BOXNAME='compose_invoicer_1'
fi

docker_installed="$( { command -v docker 1>/dev/null; } 2>&1 )"
jq_installed="$( { command -v jq 1>/dev/null; } 2>&1 )"


if [ "$docker_installed" -ne "0" ]; then
    echo "Docker is not installed"
    exit 1
fi

if  [ "$jq_installed" -ne "0" ]; then
    echo "jq is not installed"
    exit 1
fi

if [ "$(id -u)" -ne "0" ]; then
    echo "This tool must be run as root"
    exit 1
fi

if [ "$(docker ps -a | grep -c ${BOXNAME})" = 1 ]; then
    if [ "$(docker inspect ${BOXNAME} | jq '.[0].State.Status' | sed 's/"//g; ')" = "running" ]; then
        if [ "$(docker inspect ${BOXNAME} | jq '.[0].State.Health.Status' | sed 's/"//g; ')" = "null" ]; then
            echo "Healthcheck doesn't exist"
            exit 0
        fi
        if [ "$(docker inspect ${BOXNAME} | jq '.[0].State.Health.Status' | sed 's/"//g; ')" = "starting" ]; then
            echo "Healthcheck still initializing"
            exit 0
        fi
        if [ "$(docker inspect ${BOXNAME} | jq '.[0].State.Health.Status' | sed 's/"//g; ')" = "healthy" ]; then
            echo "All good"
            exit 0
        else
            echo "Attempting to restart ${BOXNAME}"
            docker stop ${BOXNAME}
            docker start ${BOXNAME}
            exit 0
        fi
    fi
fi

