#!/bin/sh

# Node management tool

if [ "$1" = "info" ]; then
  # bitcoind and lnd information
  echo "bitcoind info:"
  docker exec -it compose_btcbox_1 bitcoin-cli -getinfo
  echo "lnd info:"
  docker exec -it compose_lndbox_1 lncli getinfo
elif [ "$1" = "unlock" ]; then
  # unlock lnd wallet
  docker exec -it compose_lndbox_1 lncli unlock
elif [ "$1" = "create" ]; then
  # create lnd wallet
  docker exec -it compose_lndbox_1 lncli create
elif [ "$1" = "start" ]; then
  service docker-compose start
elif [ "$1" = "stop" ]; then
  echo "Attempting clean shutdown of bitcoind and lnd nodes"
  docker exec -it compose_lndbox_1 lncli stop
  docker exec -it compose_btcbox_1 bitcoin-cli stop
  CHECKLNDSTOPPED=1
  CHECKBTCSTOPPED=1
  # Give about 10 seconds before we kill it anyway
  while [ $(docker ps | grep -c compose_lndbox_1) == 1 ] && [ $CHECKLNDSTOPPED -lt 10 ];
  do
    let CHECKLNDSTOPPED=CHECKLNDSTOPPED+1;
    sleep 1
  done
  while [ $(docker ps | grep -c compose_btcbox_1) == 1 ] && [ $CHECKBTCSTOPPED -lt 10 ];
  do
    let CHECKBTCSTOPPED=CHECKBTCSTOPPED+1;
    sleep 1
  done  
  # Stop docker compose
  service docker-compose stop
elif [ "$1" = "restart" ]; then
  echo "Attempting clean shutdown of bitcoind and lnd nodes"
  docker exec -it compose_lndbox_1 lncli stop
  docker exec -it compose_btcbox_1 bitcoin-cli stop
  service docker-compose restart
elif [ "$1" = "btclog" ]; then
  # slow, robust method
  #docker logs -f compose_btcbox_1
  tail -f /media/volatile/bitcoin/debug.log
elif [ "$1" = "lndlog" ]; then
  # slow, robust method
  #docker logs -f compose_lndbox_1
  tail -f /media/volatile/lnd/logs/bitcoin/mainnet/lnd.log
elif [ "$1" = "temp" ]; then
  # CPU temperature
  cpu=$(cat /sys/class/thermal/thermal_zone0/temp)
  echo "CPU: $((cpu/1000))C"
else
  echo -e "Mana: node management\n"
  echo "Must pass one of:"
  echo "info, unlock, create, stop, start, restart, btclog, lndlog, temp"
fi
